// GENERATED by scripts/generate_rf_channels.py from data/rf_channels.json -- do not edit.
//
// The channel table, as the operator sees it. Every field is per channel: two
// channels may deliberately differ in more than frequency, which is what makes
// side-by-side PHY tests possible without a rebuild.

#pragma once

#include <Arduino.h>

namespace RaceLinkChannels {

struct Channel {
  uint8_t     id;            // 1-based, the number the operator picks
  const char* name;          // "Default", "Alt-1", ...
  uint32_t    freq_hz;
  uint16_t    bw_khz_x10;
  uint8_t     sf;
  uint8_t     cr_den;
  uint8_t     sync_word;
  int8_t      tx_power_dbm;
  uint16_t    preamble;
};

struct Region {
  const char*    id;         // "EU868"
  const char*    label;      // "EU" -- what the info line and the dropdown show
  uint16_t       band;       // 868 / 915 -- shown beside the label, not enforced
  const Channel* channels;
  uint8_t        count;
};

static const Channel CHANNELS_EU868[] = {
  { 1, "Default", 867700000UL, 1250, 7, 5, 18, 14, 8 },
  { 2, "Alt-1", 868200000UL, 1250, 7, 5, 18, 14, 8 },
  { 3, "Alt-2", 868700000UL, 1250, 7, 5, 18, 14, 8 },
  { 4, "Alt-3", 869200000UL, 1250, 7, 5, 18, 14, 8 },
  { 5, "High", 869700000UL, 1250, 7, 5, 18, 14, 8 },
};

static const Channel CHANNELS_US915[] = {
  { 1, "Default", 904300000UL, 1250, 7, 5, 18, 14, 8 },
  { 2, "Alt-1", 905300000UL, 1250, 7, 5, 18, 14, 8 },
  { 3, "Alt-2", 906300000UL, 1250, 7, 5, 18, 14, 8 },
  { 4, "Alt-3", 907300000UL, 1250, 7, 5, 18, 14, 8 },
  { 5, "High", 908300000UL, 1250, 7, 5, 18, 14, 8 },
};

static const uint8_t REGION_COUNT = 2;
static const Region REGIONS[REGION_COUNT] = {
  { "EU868", "EU", 868, CHANNELS_EU868, 5 },
  { "US915", "FCC", 915, CHANNELS_US915, 5 },
};

// Index into REGIONS, or REGION_COUNT when nothing matches. Callers treat
// REGION_COUNT as "custom" rather than substituting a default -- a node on an
// unrecognised frequency should say so, not claim to be on a channel it is not.
static const uint8_t REGION_NONE = REGION_COUNT;
static const uint8_t CHANNEL_NONE = 0;

inline const Region* region(uint8_t index) {
  return index < REGION_COUNT ? &REGIONS[index] : nullptr;
}

inline const Channel* channel(uint8_t regionIndex, uint8_t channelId) {
  const Region* r = region(regionIndex);
  if (!r) return nullptr;
  for (uint8_t i = 0; i < r->count; ++i) {
    if (r->channels[i].id == channelId) return &r->channels[i];
  }
  return nullptr;
}

// Reverse lookup: which channel do these PHY settings correspond to?
//
// This is the bridge from the wire protocol, which carries PHY values rather
// than a channel number (OPC_RF_CONFIG / P_RfConfig). Every field has to match:
// two channels may share a frequency and differ in spreading factor, and
// answering "channel 3" for settings that are not channel 3 would be worse than
// answering "custom".
inline bool identify(uint32_t freq_hz, uint16_t bw_khz_x10, uint8_t sf, uint8_t cr_den,
                     uint8_t sync_word, int8_t tx_power_dbm, uint16_t preamble,
                     uint8_t& regionIndex, uint8_t& channelId) {
  for (uint8_t i = 0; i < REGION_COUNT; ++i) {
    for (uint8_t j = 0; j < REGIONS[i].count; ++j) {
      const Channel& c = REGIONS[i].channels[j];
      if (c.freq_hz == freq_hz && c.bw_khz_x10 == bw_khz_x10 && c.sf == sf &&
          c.cr_den == cr_den && c.sync_word == sync_word &&
          c.tx_power_dbm == tx_power_dbm && c.preamble == preamble) {
        regionIndex = i;
        channelId = c.id;
        return true;
      }
    }
  }
  regionIndex = REGION_NONE;
  channelId = CHANNEL_NONE;
  return false;
}

}  // namespace RaceLinkChannels
