"""Generate ``racelink_rf_channels.h`` from ``data/rf_channels.json``.

The firmware needs the channel table for three things the host cannot do for
it: the channel dropdown in the WLED usermod settings, the info line, and the
band lock. Hand-maintaining a second copy of the table in C is exactly how a
channel ends up meaning one thing in the host and another on a node — so the
header is generated, checked in, and re-compared by ``tests/test_rf_channels.py``.

The band a region belongs to is not in the JSON: the host's table does not carry
it, and the same mapping already lives in the flasher (``src/rf.ts``). It is
declared here rather than added to the vendored file, so the file stays a
verbatim mirror of the host's.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLE = ROOT / "data" / "rf_channels.json"
HEADER = ROOT / "racelink_rf_channels.h"

# Region id -> (short operator-facing label, band in MHz).
#
# The band is what the region dropdown shows beside its label ("EU (868 MHz)"),
# and it matches the `bands` entries in the flasher's data/devices.json, which
# is a hardware property of a board -- a differently populated LoRa module. It
# is descriptive only: nothing on the device enforces it, because the host
# configures a gateway's radio and has no region concept to enforce against.
REGIONS = {
    "EU868": ("EU", 868),
    "US915": ("FCC", 915),
}

BANNER = "// GENERATED by scripts/generate_rf_channels.py from data/rf_channels.json -- do not edit."


def render(table: dict) -> str:
    regions = table["regions"]
    unknown = set(regions) - set(REGIONS)
    if unknown:
        raise SystemExit(
            f"data/rf_channels.json has region(s) {sorted(unknown)} with no band mapping. "
            "Add them to REGIONS in this script before releasing, or the band lock cannot "
            "decide what they belong to."
        )

    out: list[str] = [
        BANNER,
        "//",
        "// The channel table, as the operator sees it. Every field is per channel: two",
        "// channels may deliberately differ in more than frequency, which is what makes",
        "// side-by-side PHY tests possible without a rebuild.",
        "",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "namespace RaceLinkChannels {",
        "",
        "struct Channel {",
        "  uint8_t     id;            // 1-based, the number the operator picks",
        "  const char* name;          // \"Default\", \"Alt-1\", ...",
        "  uint32_t    freq_hz;",
        "  uint16_t    bw_khz_x10;",
        "  uint8_t     sf;",
        "  uint8_t     cr_den;",
        "  uint8_t     sync_word;",
        "  int8_t      tx_power_dbm;",
        "  uint16_t    preamble;",
        "};",
        "",
        "struct Region {",
        "  const char*    id;         // \"EU868\"",
        "  const char*    label;      // \"EU\" -- what the info line and the dropdown show",
        "  uint16_t       band;       // 868 / 915 -- shown beside the label, not enforced",
        "  const Channel* channels;",
        "  uint8_t        count;",
        "};",
        "",
    ]

    for region_id in sorted(regions):
        channels = sorted(regions[region_id], key=lambda c: c["id"])
        out.append(f"static const Channel CHANNELS_{region_id}[] = {{")
        for c in channels:
            out.append(
                f"  {{ {c['id']}, \"{c['name']}\", {c['freq_hz']}UL, {c['bw_khz_x10']}, "
                f"{c['sf']}, {c['cr_den']}, {c['sync_word']}, {c['tx_power_dbm']}, {c['preamble']} }},"
            )
        out.append("};")
        out.append("")

    out.append("static const uint8_t REGION_COUNT = %d;" % len(regions))
    out.append("static const Region REGIONS[REGION_COUNT] = {")
    for region_id in sorted(regions):
        label, band = REGIONS[region_id]
        count = len(regions[region_id])
        out.append(
            f'  {{ "{region_id}", "{label}", {band}, CHANNELS_{region_id}, {count} }},'
        )
    out.append("};")
    out.extend(
        [
            "",
            "// Index into REGIONS, or REGION_COUNT when nothing matches. Callers treat",
            "// REGION_COUNT as \"custom\" rather than substituting a default -- a node on an",
            "// unrecognised frequency should say so, not claim to be on a channel it is not.",
            "static const uint8_t REGION_NONE = REGION_COUNT;",
            "static const uint8_t CHANNEL_NONE = 0;",
            "",
            "inline const Region* region(uint8_t index) {",
            "  return index < REGION_COUNT ? &REGIONS[index] : nullptr;",
            "}",
            "",
            "inline const Channel* channel(uint8_t regionIndex, uint8_t channelId) {",
            "  const Region* r = region(regionIndex);",
            "  if (!r) return nullptr;",
            "  for (uint8_t i = 0; i < r->count; ++i) {",
            "    if (r->channels[i].id == channelId) return &r->channels[i];",
            "  }",
            "  return nullptr;",
            "}",
            "",
            "// Reverse lookup: which channel do these PHY settings correspond to?",
            "//",
            "// This is the bridge from the wire protocol, which carries PHY values rather",
            "// than a channel number (OPC_RF_CONFIG / P_RfConfig). Every field has to match:",
            "// two channels may share a frequency and differ in spreading factor, and",
            "// answering \"channel 3\" for settings that are not channel 3 would be worse than",
            "// answering \"custom\".",
            "inline bool identify(uint32_t freq_hz, uint16_t bw_khz_x10, uint8_t sf, uint8_t cr_den,",
            "                     uint8_t sync_word, int8_t tx_power_dbm, uint16_t preamble,",
            "                     uint8_t& regionIndex, uint8_t& channelId) {",
            "  for (uint8_t i = 0; i < REGION_COUNT; ++i) {",
            "    for (uint8_t j = 0; j < REGIONS[i].count; ++j) {",
            "      const Channel& c = REGIONS[i].channels[j];",
            "      if (c.freq_hz == freq_hz && c.bw_khz_x10 == bw_khz_x10 && c.sf == sf &&",
            "          c.cr_den == cr_den && c.sync_word == sync_word &&",
            "          c.tx_power_dbm == tx_power_dbm && c.preamble == preamble) {",
            "        regionIndex = i;",
            "        channelId = c.id;",
            "        return true;",
            "      }",
            "    }",
            "  }",
            "  regionIndex = REGION_NONE;",
            "  channelId = CHANNEL_NONE;",
            "  return false;",
            "}",
            "",
            "}  // namespace RaceLinkChannels",
            "",
        ]
    )
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the checked-in header differs from what this would write.",
    )
    args = parser.parse_args()

    rendered = render(json.loads(TABLE.read_text(encoding="utf-8")))

    if args.check:
        current = HEADER.read_text(encoding="utf-8") if HEADER.is_file() else ""
        if current != rendered:
            print(
                f"error: {HEADER.name} is out of date. Run scripts/generate_rf_channels.py.",
            )
            return 1
        print(f"{HEADER.name} matches data/rf_channels.json")
        return 0

    HEADER.write_text(rendered, encoding="utf-8")
    print(f"Wrote {HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
